INSERT INTO tipo_classificazione_dewey VALUES ("000","000","Informatica, scienze dell'informazione, opere generali");
INSERT INTO tipo_classificazione_dewey VALUES ("000","010","Bibliografia");
INSERT INTO tipo_classificazione_dewey VALUES ("000","020","Biblioteconomia e scienza dell'informazione");
INSERT INTO tipo_classificazione_dewey VALUES ("000","030","Enciclopedie");
INSERT INTO tipo_classificazione_dewey VALUES ("000","040","Pubblicazioni Miscellanee");
INSERT INTO tipo_classificazione_dewey VALUES ("000","050","Periodici Generali");
INSERT INTO tipo_classificazione_dewey VALUES ("000","060","Accademie e Istituti culturali Fondazioni Congressi");
INSERT INTO tipo_classificazione_dewey VALUES ("000","070","Giornalismo, editoria, giornali");
INSERT INTO tipo_classificazione_dewey VALUES ("000","080","Poligrafia miscellanee generali");
INSERT INTO tipo_classificazione_dewey VALUES ("000","090","Manoscritti e libri rari");
INSERT INTO tipo_classificazione_dewey VALUES ("100","000","Filosofia e discipline connesse");
INSERT INTO tipo_classificazione_dewey VALUES ("100","110","Metafisica (filosofia speculativa)");
INSERT INTO tipo_classificazione_dewey VALUES ("100","120","Epistemologia, causalità, genere umano");
INSERT INTO tipo_classificazione_dewey VALUES ("100","130","Fenomeni e tecniche paranormali");
INSERT INTO tipo_classificazione_dewey VALUES ("100","140","Specifiche posizioni filosofiche");
INSERT INTO tipo_classificazione_dewey VALUES ("100","150","Psicologia");
INSERT INTO tipo_classificazione_dewey VALUES ("100","160","Logica");
INSERT INTO tipo_classificazione_dewey VALUES ("100","170","Etica (filosofia morale)");
INSERT INTO tipo_classificazione_dewey VALUES ("100","180","Filosofia antica, medievale, orientale");
INSERT INTO tipo_classificazione_dewey VALUES ("100","190","Filosofia occidentale moderna");
INSERT INTO tipo_classificazione_dewey VALUES ("200","000","Religione");
INSERT INTO tipo_classificazione_dewey VALUES ("200","210","Religione naturale");
INSERT INTO tipo_classificazione_dewey VALUES ("200","220","Bibbia");
INSERT INTO tipo_classificazione_dewey VALUES ("200","230","Teologia cristiana, teologia dottrinale cristiana");
INSERT INTO tipo_classificazione_dewey VALUES ("200","240","Teologia morale e devozionale cristiana");
INSERT INTO tipo_classificazione_dewey VALUES ("200","250","Chiesa cristiana e comunità. Ordini religiosi cristiani");
INSERT INTO tipo_classificazione_dewey VALUES ("200","260","Teologia cristiana sociale ed ecclesiastica");
INSERT INTO tipo_classificazione_dewey VALUES ("200","270","Storia e geografia della chiesa cristiana organizzata");
INSERT INTO tipo_classificazione_dewey VALUES ("200","280","Confessioni e sette della Chiesa cristiana");
INSERT INTO tipo_classificazione_dewey VALUES ("200","290","Altre religioni e religione comparata");
INSERT INTO tipo_classificazione_dewey VALUES ("300","000","Scienze sociali");
INSERT INTO tipo_classificazione_dewey VALUES ("300","300","Opere di carattere generale e Sociologia");
INSERT INTO tipo_classificazione_dewey VALUES ("300","310","Statistica");
INSERT INTO tipo_classificazione_dewey VALUES ("300","320","Scienze politiche");
INSERT INTO tipo_classificazione_dewey VALUES ("300","330","Scienze economiche");
INSERT INTO tipo_classificazione_dewey VALUES ("300","340","Diritto");
INSERT INTO tipo_classificazione_dewey VALUES ("300","350","Amministrazione pubblica e scienze militari");
INSERT INTO tipo_classificazione_dewey VALUES ("300","360","Assistenza sociale, sicurezza sociale");
INSERT INTO tipo_classificazione_dewey VALUES ("300","370","Educazione");
INSERT INTO tipo_classificazione_dewey VALUES ("300","380","Commercio, comunicazioni, trasporti");
INSERT INTO tipo_classificazione_dewey VALUES ("300","390","Usi e costumi, etichetta, folclore");
INSERT INTO tipo_classificazione_dewey VALUES ("400","000","Linguistica");
INSERT INTO tipo_classificazione_dewey VALUES ("400","410","Linguistica");
INSERT INTO tipo_classificazione_dewey VALUES ("400","420","Lingue inglese e anglosassone");
INSERT INTO tipo_classificazione_dewey VALUES ("400","430","Lingue germaniche. Tedesco");
INSERT INTO tipo_classificazione_dewey VALUES ("400","440","Lingue romanze. Francese");
INSERT INTO tipo_classificazione_dewey VALUES ("400","450","Lingue italiana, rumena e affini");
INSERT INTO tipo_classificazione_dewey VALUES ("400","460","Lingue spagnola e portoghese");
INSERT INTO tipo_classificazione_dewey VALUES ("400","470","Lingue italiche. Latino");
INSERT INTO tipo_classificazione_dewey VALUES ("400","480","Lingue elleniche. Greco classico");
INSERT INTO tipo_classificazione_dewey VALUES ("400","490","Altre lingue");
INSERT INTO tipo_classificazione_dewey VALUES ("500","000","Scienze pure");
INSERT INTO tipo_classificazione_dewey VALUES ("500","510","Matematica");
INSERT INTO tipo_classificazione_dewey VALUES ("500","520","Astronomia e scienze connesse");
INSERT INTO tipo_classificazione_dewey VALUES ("500","530","Fisica");
INSERT INTO tipo_classificazione_dewey VALUES ("500","540","Chimica e scienze connesse");
INSERT INTO tipo_classificazione_dewey VALUES ("500","550","Scienze della terra e di altri mondi");
INSERT INTO tipo_classificazione_dewey VALUES ("500","560","Paleontologia. Paleozoologia");
INSERT INTO tipo_classificazione_dewey VALUES ("500","570","Scienze della vita");
INSERT INTO tipo_classificazione_dewey VALUES ("500","580","Scienze botaniche");
INSERT INTO tipo_classificazione_dewey VALUES ("500","590","Scienze zoologiche");
INSERT INTO tipo_classificazione_dewey VALUES ("600","000","Tecnologia (Scienze applicate)");
INSERT INTO tipo_classificazione_dewey VALUES ("600","610","Medicina e salute");
INSERT INTO tipo_classificazione_dewey VALUES ("600","620","Ingegneria e attivita' affini");
INSERT INTO tipo_classificazione_dewey VALUES ("600","630","Agricoltura e tecniche connesse");
INSERT INTO tipo_classificazione_dewey VALUES ("600","640","Gestione della casa e della famiglia");
INSERT INTO tipo_classificazione_dewey VALUES ("600","650","Direzione aziendale e servizi ausiliari");
INSERT INTO tipo_classificazione_dewey VALUES ("600","660","Tecnologie chimiche e affini");
INSERT INTO tipo_classificazione_dewey VALUES ("600","670","Manifatture");
INSERT INTO tipo_classificazione_dewey VALUES ("600","680","Manifattura di prodotti per usi specifici");
INSERT INTO tipo_classificazione_dewey VALUES ("600","690","Edilizia");
INSERT INTO tipo_classificazione_dewey VALUES ("700","000","Arti, belle arti e arti decorative");
INSERT INTO tipo_classificazione_dewey VALUES ("700","710","Urbanistica e arte del paesaggio");
INSERT INTO tipo_classificazione_dewey VALUES ("700","720","Architettura");
INSERT INTO tipo_classificazione_dewey VALUES ("700","730","Arti plastiche, scultura");
INSERT INTO tipo_classificazione_dewey VALUES ("700","740","Disegno, arti decorative e arti minori");
INSERT INTO tipo_classificazione_dewey VALUES ("700","750","Pittura e pitture");
INSERT INTO tipo_classificazione_dewey VALUES ("700","760","Arti grafiche, tecniche di impressione e stampe");
INSERT INTO tipo_classificazione_dewey VALUES ("700","770","Fotografia");
INSERT INTO tipo_classificazione_dewey VALUES ("700","780","Musica");
INSERT INTO tipo_classificazione_dewey VALUES ("700","790","Arti ricreative e dello spettacolo");
INSERT INTO tipo_classificazione_dewey VALUES ("800","000","Letteratura");
INSERT INTO tipo_classificazione_dewey VALUES ("800","810","Letteratura americana in lingua inglese");
INSERT INTO tipo_classificazione_dewey VALUES ("800","820","Letteratura in lingua inglese e anglosassone");
INSERT INTO tipo_classificazione_dewey VALUES ("800","830","Letterature nelle lingue germaniche. Letteratura tedesca");
INSERT INTO tipo_classificazione_dewey VALUES ("800","840","Letterature nelle lingue romanze. Letteratura francese");
INSERT INTO tipo_classificazione_dewey VALUES ("800","850","Letterature in lingua italiana, rumena e affini");
INSERT INTO tipo_classificazione_dewey VALUES ("800","860","Letterature in lingua spagnola e portoghese");
INSERT INTO tipo_classificazione_dewey VALUES ("800","870","Letterature nelle lingue italiche. Letteratura latina");
INSERT INTO tipo_classificazione_dewey VALUES ("800","880","Letterature nelle lingue elleniche. Letteratura greca classica");
INSERT INTO tipo_classificazione_dewey VALUES ("800","890","Letterature in altre lingue");
INSERT INTO tipo_classificazione_dewey VALUES ("900","000","Geografia, storia e discipline ausiliarie");
INSERT INTO tipo_classificazione_dewey VALUES ("900","910","Geografia generale, viaggi");
INSERT INTO tipo_classificazione_dewey VALUES ("900","920","Biografie generali, genealogia, araldica");
INSERT INTO tipo_classificazione_dewey VALUES ("900","930","Storia generale del mondo antico");
INSERT INTO tipo_classificazione_dewey VALUES ("900","940","Storia generale dell'Europa");
INSERT INTO tipo_classificazione_dewey VALUES ("900","950","Storia generale dell'Asia");
INSERT INTO tipo_classificazione_dewey VALUES ("900","960","Storia generale dell'Africa");
INSERT INTO tipo_classificazione_dewey VALUES ("900","970","Storia dell'America settentrionale");
INSERT INTO tipo_classificazione_dewey VALUES ("900","980","Storia generale dell'America meridionale");
INSERT INTO tipo_classificazione_dewey VALUES ("900","990","Storia generale di altre parti del mondo e di mondi extraterrestri");
